---
# File: playbook.yml
# Web Servers
- hosts: webserver
  become: yes
  become_method: sudo
  roles:
    - systools
    - oh-my-zsh
    - apache2
    - php5
    - mysql
    - phpmyadmin
    - composer
    - exim

  
# - hosts: ilias
#   become: yes
#   become_method: sudo
#   roles:
#     - InstILIAS

# - hosts: generali
#   become: yes
#   become_method: sudo
#   roles:
#     - catILIAS