---
# File: playbook.yml

- hosts: webserver
  become: yes
  become_method: sudo
  roles:
    - systools
    - apache2
    - php5
    - php-tools
    - mysql
    - phpmyadmin
    - oh-my-zsh
    - ssmtp
    - ssh-conf

- hosts: mailserver
  become: yes
  become_method: sudo
  roles:
    - exim
    - dovecot
