---
# File: playbook.yml
# Web Servers
- hosts: webserver
  become: yes
  become_method: sudo
  roles:
    - systools
    - oh-my-zsh
    - apache2
    - php5
    - mysql
    - phpmyadmin
    - ssmtp

  
- hosts: ilias
  become: yes
  become_method: sudo
  roles:
    - systools
    - oh-my-zsh
    - apache2
    - php5
    - mysql
    - php-tools
    - phpmyadmin
    - InstILIAS

- hosts: generali
  roles:
    - catILIAS

- hosts: mail
  become: yes
  become_method: sudo
  roles:
    - exim
    - dovecot