---
# File: playbook.yml
# Web Servers
- hosts: webserver
  become: yes
  become_method: sudo
  roles:
    - systools
    - apache2
    - php5-fpm
    - mysql
    - achaussier.phpmyadmin
  
- hosts: ilias
  become: yes
  become_method: sudo
  roles:
    - InstILIAS