---
# File: roles/systools/tasks/main.yml

- name:         install | ensure that non-free packages are used
  replace:
    dest:       /etc/apt/sources.list
    regexp:     '(^deb(-src?) http(s?):\/\/.*\/.* main$)'
    replace:    '\1 non-free'

- name:         install | enforce update of apt cache
  apt:          update_cache=yes

- name:         install | ensure that systools will be installed
  apt:          name="{{item}}" state=latest update_cache=yes cache_valid_time=3600
  with_items:   "{{sys_packages}}"
  when:         "{{sys_packages}}"

- name:         copy | disable ipv6 on every boot
  copy:         src=roles/systools/templates/01-disable-ipv6.conf dest=/etc/sysctl.d/01-disable-ipv6.conf owner={{user}} mode="u+x"

- name:         command | disable ipv6 now
  command:      echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6

# - name:         Copy /etc/sudoers.d/ssh_auth_sock into place
#   copy:         content='Defaults env_keep += "SSH_AUTH_SOCK"' dest='/etc/sudoers.d/ssh_auth_sock' validate='visudo -cf %s' owner=root group=root mode=0440