---
# File: roles/systools/tasks/main.yml

- name:         install | ensure that non-free packages are used
  replace:
    dest:       /etc/apt/sources.list
    regexp:     '(^deb(-src?) http(s?):\/\/.*\/.* main$)'
    replace:    '\1 non-free'

- name:         install | enforce update of apt cache
  apt:          update_cache=yes

- name:         install | ensure that systools will be installed
  apt:          name="{{item}}" state=latest update_cache=yes cache_valid_time=3600
  with_items:   "{{systools}}"
  when:         "{{systools}}"

- name:         copy | disable ipv6 on every boot
  copy:         src=roles/systools/templates/01-disable-ipv6.conf dest=/etc/sysctl.d/01-disable-ipv6.conf owner=root mode="u+x"

- name:         command | disable ipv6 now
  command:      echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6

- name:         ensure git is globaly set to my name
  command:      git config --global user.name "daniwe4"

- name:         ensure git is globaly set to my email
  command:      git config --global user.email "daniel.weise@concepts-and-training"