---
# File: roles/php-fpm/defaults/main.yml
# Package to install
php5_packages:
  - imagemagick
  - php5
  - php5-fpm
  - php5-cli
  - php5-common
  - php5-curl
  - php5-gd
  - php5-imagick
  - php5-mysql
  - php5-xsl

# Configuration
php5_timezone:  Europe/Berlin
php5_fpm_pools:
  - name:       www
    user:       www-data
    group:      www-data
    socket:     /var/run/php5-fpm.sock

# ...