---
# File: roles/mysql/tasks/main.yml
# Install and configure mysql

- name:           install | Install the mysql packages in Debian derivatives
  apt:            name={{ item }} state=installed update_cache=yes
  with_items:     "{{mysql_pkgs}}"
  environment:    "{{env}}"
  when:           ansible_os_family == 'Debian'

- name:           template | Copy the my.cnf file 
  template:       src=my.cnf.{{ ansible_os_family }}.j2 dest={{ mysql_conf_dir }}/my.cnf
  notify:         restart mysql

- name:           file | Create the directory /etc/mysql/conf.d
  file:           path=/etc/mysql/conf.d state=directory
  notify:         restart mysql

- name:           service | Start the mysql services Redhat
  service:        name={{ mysql_service }} state=started enabled=yes

- name:           mysql | update mysql root password for all root accounts
  mysql_user:     name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when:           ansible_hostname != 'localhost'

- name:           mysql | update mysql root password for all root accounts
  mysql_user:     name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
  when:           ansible_hostname == 'localhost' 

- name:           template | copy .my.cnf file with root password credentials
  template:       src=.my.cnf.j2 dest=~/.my.cnf mode=0600

- name:           mysql | ensure anonymous users are not in the database
  mysql_user:     name='' host={{ item }} state=absent
  with_items:
   - localhost
   - "{{ ansible_hostname }}"

- name:           mysql | remove the test database
  mysql_db:       name=test state=absent


