---
# File: roles/InstILIAS/tasks/main.yml
# Clone InstILIAS to /var/www/default

- name:         copy id_rsa
  copy:
    src:        /Users/dw/id_rsa
    dest:       /home/vagrant/.ssh/
    owner:      "vagrant"

- name:         git | get InstILIAS
  git:          repo=git@github.com:daniwe4/ilias-tool-InstILIAS.git
                dest=/home/vagrant/InstILIAS
                version={{InstILIAS_version}}
                accept_hostkey=yes
                force=yes
                recursive=no
                key_file=/home/vagrant/.ssh/id_rsa

- name:         shell | start composer
  shell:        composer install
  args:
    chdir:      /home/vagrant/InstILIAS

- name:         file | copy InstILIAS config file
  template:
    src:        roles/InstILIAS/templates/config.yml.j2
    dest:       /home/vagrant/InstILIAS/src/config.yaml

- name:         shell | start InstILIAS
  shell:        php src/bin/install.php src/config.yaml non_interactiv
  args:
    chdir:      /home/vagrant/InstILIAS

- name:         file | change privilegs
  file:
    path:       /home/vagrant/share/repo/data
    state:      directory
    owner:      www-data
    group:      www-data
    recurse:    yes